import Head from 'next/head'
import Image from 'next/image';
import Link from 'next/link';


import styles from '../styles/Home.module.scss';
import burgerIcon from '../assets/burgerIcon.svg';
import { GetServerSideProps } from 'next';

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fast Burger | Início</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.content}> 
        <Image src={burgerIcon} alt="burger logo"/>

        <Link href="/confirmRequest">
          <a>Realizar pedido</a>
        </Link>
        <Link href="/historic">
          <a>Ver histórico</a>
        </Link>
      </div>
    </div>
  )
};

export const getServerSideProps: GetServerSideProps = async(ctx) => {
  const response = await fetch('https://api.github.com/users/joaovictor3g/repos');

  const dataJson = await response.json();
  const data = dataJson;
  
  return {
    props: {
      data
    }
  }
}
